Controllers/RidesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RideSharing.Data;
using RideSharing.Models;
using RideSharing.ViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;
using RideSharing.Services;

namespace RideSharing.Controllers
{
    [Authorize]
    public class RidesController : Controller
    {
        private readonly RideSharingContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;
        private readonly GoogleMapsService _googleMapsService;

        public RidesController(RideSharingContext context, UserManager<ApplicationUser> userManager, IMapper mapper, GoogleMapsService googleMapsService)
        {
            _context = context;
            _userManager = userManager;
            _mapper = mapper;
            _googleMapsService = googleMapsService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Challenge();
            }
            var currentDateTime = DateTime.UtcNow;
            var userId = user.Id;
            var rides = await _context.Rides
                .Where(r => r.DriverId == userId)
                .Include(r => r.Vehicle)
                 .Include(r => r.RideRequests)
                .ToListAsync();

            return View(rides);
        }

        public async Task<IActionResult> Create()
        {
            var userId = _userManager.GetUserId(User);
            var vehicles = await _context.Vehicles
                .Where(v => v.DriverId == userId)
                .ToListAsync();

            var model = new RideCreateViewModel();
            ViewBag.Vehicles = new SelectList(vehicles, "Id", "LicensePlate");

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RideCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var vehicles = await _context.Vehicles
                    .Where(v => v.DriverId == userId)
                    .ToListAsync();

                ViewBag.Vehicles = new SelectList(vehicles, "Id", "LicensePlate", model.VehicleId);
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Unauthorized();
            }

            var selectedVehicle = await _context.Vehicles.FindAsync(model.VehicleId);
            if (selectedVehicle != null && model.AvailableSeats > selectedVehicle.Capacity)
            {
                ModelState.AddModelError("AvailableSeats", "Available seats cannot exceed the vehicle capacity.");
                ViewBag.Vehicles = new SelectList(await _context.Vehicles
                    .Where(v => v.DriverId == user.Id).ToListAsync(), "Id", "LicensePlate", model.VehicleId);
                return View(model);
            }

            var ride = _mapper.Map<Ride>(model);
            ride.DriverId = user.Id;
            ride.CreatedAt = DateTime.UtcNow;
            ride.UpdatedAt = DateTime.UtcNow;

            _context.Add(ride);

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error saving ride: " + ex.Message);
                ModelState.AddModelError("", "An error occurred while saving the ride.");
                var vehicles = await _context.Vehicles
                    .Where(v => v.DriverId == user.Id)
                    .ToListAsync();
                ViewBag.Vehicles = new SelectList(vehicles, "Id", "LicensePlate", model.VehicleId);
                return View(model);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ride = await _context.Rides.FindAsync(id);
            if (ride == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<RideEditViewModel>(ride);

            var vehicles = await _context.Vehicles
                .Where(v => v.DriverId == ride.DriverId)
                .ToListAsync();

            ViewBag.Vehicles = new SelectList(vehicles, "Id", "LicensePlate", ride.VehicleId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, RideEditViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                var vehicles = await _context.Vehicles
                    .Where(v => v.DriverId == _userManager.GetUserId(User))
                    .ToListAsync();
                ViewBag.Vehicles = new SelectList(vehicles, "Id", "LicensePlate", model.VehicleId);
                return View(model);
            }

            var ride = await _context.Rides.FindAsync(id);
            if (ride == null)
            {
                return NotFound();
            }

            var selectedVehicle = await _context.Vehicles.FindAsync(model.VehicleId);
            if (selectedVehicle != null && model.AvailableSeats > selectedVehicle.Capacity)
            {
                ModelState.AddModelError("AvailableSeats", "Available seats cannot exceed the vehicle capacity.");
                ViewBag.Vehicles = new SelectList(await _context.Vehicles
                    .Where(v => v.DriverId == _userManager.GetUserId(User)).ToListAsync(), "Id", "LicensePlate", model.VehicleId);
                return View(model);
            }

            _mapper.Map(model, ride);
            ride.UpdatedAt = DateTime.UtcNow;

            try
            {
                _context.Update(ride);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RideExists(ride.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ride = await _context.Rides
                .Include(r => r.Vehicle)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ride == null)
            {
                return NotFound();
            }

            return View(ride);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ride = await _context.Rides.FindAsync(id);
            if (ride != null)
            {
                _context.Rides.Remove(ride);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ride = await _context.Rides
                .Include(r => r.Vehicle)
                .Include(r => r.Driver)
                .Include(r => r.RideRequests)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (ride == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            string userId = user?.Id;

            RideRequest existingRequest = null;
            if (!string.IsNullOrEmpty(userId))
            {
                    existingRequest = await _context.RideRequests
                        .Where(rr => rr.RideId == id && rr.PassengerId == userId && rr.Status != "Deleted")
                        .OrderByDescending(rr => rr.RequestedAt)
                        .FirstOrDefaultAsync();
            }

            bool hasAcceptedRequest = ride.RideRequests.Any(rr => rr.Status == "Accepted" || rr.Status == "Pending");
            ViewBag.HasAcceptedRequest = hasAcceptedRequest;

            var model = new RideDetailsViewModel
            {
                Id = ride.Id,
                DriverEmail = ride.Driver.Email,
                DriverId = ride.DriverId,
                VehicleName = ride.Vehicle.Model,
                Origin = ride.Origin,
                Destination = ride.Destination,
                RideDateTime = ride.RideDateTime,
                AvailableSeats = ride.AvailableSeats,
                PricePerSeat = ride.PricePerSeat,
                PickupLocation = ride.PickupLocation,
                RideDescription = ride.RideDescription,
                ExistingRequestStatus = existingRequest?.Status,
                TotalDistance = ride.TotalDistance,
                TotalDuration = ride.TotalDuration
            };

            return View(model);
        }

        private bool RideExists(int id)
        {
            return _context.Rides.Any(e => e.Id == id);
        }
        [HttpGet]
        [Route("api/maps/getRouteInfo")]
        public async Task<IActionResult> GetRouteInfo(string origin, string destination)
        {
            if (string.IsNullOrEmpty(origin) || string.IsNullOrEmpty(destination))
             {
                return BadRequest(new { message = "Origin and destination are required." });

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RideSharing</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RideSharing.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RideSharing</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="navbar-nav flex-grow-1">
                                                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Rides</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="RideRequests" asp-action="Index">My Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Vehicles" asp-action="Index">My vehicles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Rides" asp-action="Index">My rides</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="RideRequests" asp-action="MyIncomingRequests">Incoming requests</a>
                        </li>
                    </ul>
                    @using Microsoft.AspNetCore.Identity
                    @inject SignInManager<ApplicationUser> SignInManager
                    <ul class="navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        @await Html.PartialAsync("_LoginPartial")
                    }
                    else
                    {
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="/Identity/Account/Login">Login</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link text-dark" href="/Identity/Account/Register">Register</a>
                    </li>
                    }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - RideSharing - <a asp-area="" asp-controller="Home"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>